name: sweep-1
project: thesis
run_cap: 40
command:
  - thesis
  - --threads=4
  - train
  - --dataset=solutions/data/big-gen-toy-100k
  - --batch=128
  - --max-epochs=10
  - --num-workers=4
  - --run-name=sweep-1-run
  - ${args}
method: bayes
metric:
  name: val_loss_epoch
  goal: minimize
parameters:
  lr:
    values: [0.0001, 0.0003, 0.001, 0.003]
  num-layers:
    values: [4, 6, 8, 12, 18]
  num-heads:
    values: [4, 8, 16, 32]
  hidden-channels:
    values: [16, 32, 64, 128, 256]
