name: sweep-3
project: thesis
run_cap: 150
command:
  - thesis
  - --threads=4
  - train
  - --dataset=solutions/data/nov-24-preference-fix
  - --batch=64
  - --max-epochs=15
  - --num-workers=4
  - --run-name=sweep-4
  - ${args}
method: bayes
metric:
  name: val_loss_epoch
  goal: minimize
parameters:
  lr:
    values: [0.0001, 0.0003, 0.001, 0.003]
  num-layers:
    values: [2, 3, 6, 10, 15, 23, 34, 50, 75]
  num-heads:
    values: [2, 4, 8, 16]
  hidden-channels:
    values: [16, 24, 36, 54, 81, 122]
